---
  extends:
    - eslint:recommended
    - plugin:prettier/recommended
  env:
    browser: true
    jest: true
  plugins:
    - "@typescript-eslint"
  parser: "@typescript-eslint/parser"
  parserOptions:
    sourceType: module
    project: "./tsconfig.json"
  rules:
    prettier/prettier: 
      - error
      - 
        "no-unused-vars": "off"
        "@typescript-eslint/no-unused-vars": "error"